server:
  uri: http://localhost
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: z.zanatciu@gmail.com
    password: arbielezi123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

